package com.thekrayem.cryptoapp.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CHAT_MESSAGE".
 */
public class chat_message {

    private Long chat_message_id;
    private String chat_message_content;
    private Boolean chat_message_mine;
    private Long chat_message_user_id;
    private Long chat_message_time;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public chat_message() {
    }

    public chat_message(Long chat_message_id) {
        this.chat_message_id = chat_message_id;
    }

    public chat_message(Long chat_message_id, String chat_message_content, Boolean chat_message_mine, Long chat_message_user_id, Long chat_message_time) {
        this.chat_message_id = chat_message_id;
        this.chat_message_content = chat_message_content;
        this.chat_message_mine = chat_message_mine;
        this.chat_message_user_id = chat_message_user_id;
        this.chat_message_time = chat_message_time;
    }

    public Long getChat_message_id() {
        return chat_message_id;
    }

    public void setChat_message_id(Long chat_message_id) {
        this.chat_message_id = chat_message_id;
    }

    public String getChat_message_content() {
        return chat_message_content;
    }

    public void setChat_message_content(String chat_message_content) {
        this.chat_message_content = chat_message_content;
    }

    public Boolean getChat_message_mine() {
        return chat_message_mine;
    }

    public void setChat_message_mine(Boolean chat_message_mine) {
        this.chat_message_mine = chat_message_mine;
    }

    public Long getChat_message_user_id() {
        return chat_message_user_id;
    }

    public void setChat_message_user_id(Long chat_message_user_id) {
        this.chat_message_user_id = chat_message_user_id;
    }

    public Long getChat_message_time() {
        return chat_message_time;
    }

    public void setChat_message_time(Long chat_message_time) {
        this.chat_message_time = chat_message_time;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
