package com.thekrayem.cryptoapp.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "FILE".
 */
public class file {

    private Long file_id;
    private byte[] file_encrypted_bytes;
    private byte[] hashed_pass;
    private byte[] salt;
    private byte[] iv;
    private String file_original_name;
    private String file_encrypted_name;
    private String file_path;
    private Integer iterations;
    private Integer key_length;
    private Boolean is_chat;
    private byte[] file_hash;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public file() {
    }

    public file(Long file_id) {
        this.file_id = file_id;
    }

    public file(Long file_id, byte[] file_encrypted_bytes, byte[] hashed_pass, byte[] salt, byte[] iv, String file_original_name, String file_encrypted_name, String file_path, Integer iterations, Integer key_length, Boolean is_chat, byte[] file_hash) {
        this.file_id = file_id;
        this.file_encrypted_bytes = file_encrypted_bytes;
        this.hashed_pass = hashed_pass;
        this.salt = salt;
        this.iv = iv;
        this.file_original_name = file_original_name;
        this.file_encrypted_name = file_encrypted_name;
        this.file_path = file_path;
        this.iterations = iterations;
        this.key_length = key_length;
        this.is_chat = is_chat;
        this.file_hash = file_hash;
    }

    public Long getFile_id() {
        return file_id;
    }

    public void setFile_id(Long file_id) {
        this.file_id = file_id;
    }

    public byte[] getFile_encrypted_bytes() {
        return file_encrypted_bytes;
    }

    public void setFile_encrypted_bytes(byte[] file_encrypted_bytes) {
        this.file_encrypted_bytes = file_encrypted_bytes;
    }

    public byte[] getHashed_pass() {
        return hashed_pass;
    }

    public void setHashed_pass(byte[] hashed_pass) {
        this.hashed_pass = hashed_pass;
    }

    public byte[] getSalt() {
        return salt;
    }

    public void setSalt(byte[] salt) {
        this.salt = salt;
    }

    public byte[] getIv() {
        return iv;
    }

    public void setIv(byte[] iv) {
        this.iv = iv;
    }

    public String getFile_original_name() {
        return file_original_name;
    }

    public void setFile_original_name(String file_original_name) {
        this.file_original_name = file_original_name;
    }

    public String getFile_encrypted_name() {
        return file_encrypted_name;
    }

    public void setFile_encrypted_name(String file_encrypted_name) {
        this.file_encrypted_name = file_encrypted_name;
    }

    public String getFile_path() {
        return file_path;
    }

    public void setFile_path(String file_path) {
        this.file_path = file_path;
    }

    public Integer getIterations() {
        return iterations;
    }

    public void setIterations(Integer iterations) {
        this.iterations = iterations;
    }

    public Integer getKey_length() {
        return key_length;
    }

    public void setKey_length(Integer key_length) {
        this.key_length = key_length;
    }

    public Boolean getIs_chat() {
        return is_chat;
    }

    public void setIs_chat(Boolean is_chat) {
        this.is_chat = is_chat;
    }

    public byte[] getFile_hash() {
        return file_hash;
    }

    public void setFile_hash(byte[] file_hash) {
        this.file_hash = file_hash;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
